version: '3'

services:
  app:
    ports:
      - "12322:8082"
    image: zoe:dev
    environment:
      type: "web"
    deploy:
      replicas: 3
    volumes:
      - ./static:/home/zoe/static
  cron:
    image: zoe:dev
    environment:
      type: "cron"
    volumes:
      - ./static:/home/zoe/static