version: '3.3'
# name: flarum

services:
  postgres-db:
    image: postgres:17.5-alpine3.22
    restart: unless-stopped

    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: p@ssw0rd
      PGDATA: /data/postgres
      POSTGRES_DB: flarum
    volumes:
      - postgres:/data/postgres
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -d postgres" ]
      start_period: 5s
      # interval: 30s
      # timeout: 10s
      # retries: 5

  redis-db:
    image: redis:6.0
    volumes:
      - redis:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      start_period: 5s

      # interval: 30s
      # timeout: 10s
      # retries: 5

  go-flarum-init:
    build: .
    command:
      - /usr/local/bin/go-flarum-migration
      - -config
      - /home/go-flarum/config.yml
      - -initdb
    depends_on:
      postgres-db:
        condition: service_healthy
      redis-db:
        condition: service_healthy

  go-flarum:
    build: .
    ports:
      - "8082:8082"
    environment:
      type: "web"
    deploy:
      replicas: 1
    command:
      - /usr/local/bin/go-flarum
      - -config
      - /home/go-flarum/config.yml
      - -lvl
      - DEBUG
    volumes:
      - flarum-static:/home/go-flarum/static
    depends_on:
      postgres-db:
        condition: service_healthy
      redis-db:
        condition: service_healthy
      go-flarum-init:
        condition: service_completed_successfully

volumes:
  postgres:
    driver: local
  redis:
    driver: local
  flarum-static:
    driver: local