version: '3'

services:
  app:
    ports:
      - "8081:8082"
    image: yiqi:dev
    deploy:
      replicas: 2
    labels:
      - "com.docker.lb.hosts=demo.local"
      - "com.docker.lb.ip_hash=true"
    volumes:
      - ./static:/home/goyoubbs/static