version: '3'

services:
  app:
    ports:
      - "8081:8082"
    image: yiqi:dev
    deploy:
      replicas: 1
      labels:
        com.docker.lb.hosts: yiqi.ml
        com.docker.lb.ip_hash: 'true'
        com.docker.lb.port: 8081
    volumes:
      - ./static:/home/goyoubbs/static