version: '3'

services:
  app:
    ports:
      - "10004:8082"
    image: go-flarum:dev
    environment:
      type: "web"
    deploy:
      replicas: 3
    volumes:
      - ./static:/home/go-flarum/static
      - ./config/config.yaml-docker:/home/go-flarum/config.yml
  cron:
    image: go-flarum:dev
    environment:
      type: "cron"
    volumes:
      - ./static:/home/go-flarum/static
      - ./config/config.yaml-docker:/home/go-flarum/config.yml