version: '3'

services:
  app:
    ports:
      - "8081:8082"
    image: yiqi:dev
    environment:
      type: "web"
    deploy:
      replicas: 3
      labels:
        com.docker.lb.hosts: yiqi.ml
        com.docker.lb.ip_hash: 'true'
        com.docker.lb.port: 8081
    volumes:
      - ./static:/home/goyoubbs/static
  cron:
    image: yiqi:dev
    environment:
      type: "cron"
    volumes:
      - ./static:/home/goyoubbs/static