name: ci

on: [push]
# on:
#   push:
#     branches:
#       - 'master'

jobs:
  docker:
    runs-on: ubuntu-latest
    env:
      GO_MOD_NAME: zoe

    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: recursive

      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Login to GitHub Container Registry
        uses: docker/login-action@v1 
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Delete logs
        run: |
          sed -i '/## BOF CLEAN/,/## EOF CLEAN/d' Dockerfile  # 删除调试代码
      -
        name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            corvofeng/zoe:latest
            ghcr.io/corvofeng/zoe:latest