# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    env:
      GO_MOD_NAME: goyoubbs

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2
      with:
        submodules: true

    - name: Setup Go environment
      uses: actions/setup-go@v2.0.3

    - name: Run a multi-line script
      run: |
        go test ${GO_MOD_NAME}/util
        go test ${GO_MOD_NAME}/model
        go test ${GO_MOD_NAME}/model/flarum
